### ISSUE TITLE
Add "coming soon" message

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick-docs-zh#1]
Hi @Juan0001! Now that we have created a placeholder for the Chinese-language Yellowbrick documentation, could you translate the following statement into Chinese and add it to [index.rst](https://github.com/DistrictDataLabs/yellowbrick-docs-zh/blob/master/docs/index.rst)?

> Welcome to Yellowbrick! 
>
> We are currently working on a Chinese-language translation of the documentation, so please come back soon.
>
> Also, we're always looking for help! If you'd like to contribute to the translation, you can submit a pull request to [yellowbrick-docs-zh](https://github.com/DistrictDataLabs/yellowbrick-docs-zh). If you're interested in contributing to Yellowbrick, you can submit a pull request to the [codebase](https://github.com/DistrictDataLabs/yellowbrick).

**Comment by Juan0001** [comment]
@rebeccabilbro Off course.  I will add it on soon after I finishing translate. It won't be too long.

**Comment by rebeccabilbro** [comment]
Awesome, sounds great!

**Comment by rebeccabilbro** [comment]
Done, thanks to @Juan0001!
